package com.hirepro.users.enums;

public enum UserRole {
    SUPERADMIN,
    CLIENT_ADMIN,
    BDM,
    SALES_EXECUTIVE,
    HR_MANAGER,
    ACCOUNT_MANAGER,
    PAYROLL_SPECIALIST,
    RECRUITER,
    SR_RECRUITER,
    USIT_RECRUITER,
    USIT_COORDINATOR,
    TEAM_LEAD,
    EMPLOYEE_MANAGER,
    HR,
    EMPLOYEE,
    IT_SUPPORT,
    TRAINER,
    ONBOARDING_SPECIALIST
}